import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.js',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', 'Figtree', ...defaultTheme.fontFamily.sans],
                heading: ['Montserrat', 'sans-serif'],
                "body-lg": ["Inter"], "label-md": ["Inter"], "headline-md": ["Montserrat"],
                "title-lg": ["Montserrat"], "body-md": ["Inter"],
                "display-lg": ["Montserrat"], "display-lg-mobile": ["Montserrat"],
            },
            fontSize: {
                "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
                "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
                "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
                "title-lg": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
                "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
                "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
                "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
            },
            spacing: {
                gutter: "24px", unit: "8px", "container-max": "1280px",
                "margin-mobile": "16px", "margin-desktop": "40px",
            },
            maxWidth: {
                container: "1280px",
                "container-max": "1280px",
            },
            borderRadius: {
                DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px",
            },
            colors: {
                primary: "#031636",
                "on-primary": "#ffffff",
                "primary-container": "#1a2b4c",
                "primary-fixed-dim": "#b6c6f0",
                secondary: "#735c00",
                "on-secondary": "#ffffff",
                "secondary-container": "#fed65b",
                "secondary-fixed": "#ffe088",
                "on-secondary-container": "#745c00",
                "on-surface-variant": "#44474e",
                "surface-container-low": "#f0f3ff",
                "surface-container-highest": "#d8e3fa",
                background: "#f9f9ff", "on-surface": "#111c2c",
                outline: "#75777f", "outline-variant": "#c5c6cf",
                "on-background": "#111c2c",
                "surface": "#f9f9ff",
                "on-secondary-fixed": "#241a00",
                "on-primary-fixed": "#071b3b",
                "surface-dim": "#cfdaf1",
                "surface-bright": "#f9f9ff",
                "surface-container": "#e7eeff",
                "surface-variant": "#d8e3fa",
                "primary-fixed": "#d8e2ff",
                "secondary-fixed-dim": "#e9c349",
                "on-secondary-fixed-variant": "#574500",
                "on-primary-fixed-variant": "#364669",
                "on-primary-container": "#8293ba",
                "inverse-surface": "#263142",
                "inverse-on-surface": "#ebf1ff",
                "inverse-primary": "#b6c6f0",
                error: "#ba1a1a", "on-error": "#ffffff",
                "error-container": "#ffdad6",
                "on-error-container": "#93000a",
                "tertiary-container": "#292c2d",
                tertiary: "#151819",
                "on-tertiary": "#ffffff",
                "on-tertiary-container": "#919394",
                "tertiary-fixed": "#e1e3e4",
                "tertiary-fixed-dim": "#c5c7c8",
                "on-tertiary-fixed": "#191c1d",
                "on-tertiary-fixed-variant": "#454748",
                "surface-container-high": "#dee8ff",
                "surface-container-lowest": "#ffffff",
                "surface-tint": "#4e5e82",
            },
        },
    },

    plugins: [forms],
};
